name: Library Builds for Windows compilers

on:
    workflow_dispatch:

jobs:
    librarybuild:
      runs-on: ['win-builder']

      steps:
      - name: Download and run startup script
        run: cd /tmp && Invoke-WebRequest -Uri "https://raw.githubusercontent.com/compiler-explorer/infra/63feee2732b4b065b89645072dd23f18a326aa13/init/start-builder.ps1" -OutFile "C:\tmp\start-builder.ps1" && pwsh .\start-builder.ps1
      - name: Enter conan credentials
        run: $env:CONAN_USER = "ce" && $env:CONAN_PASSWORD = "${{ secrets.CONAN_PASSWORD }}"
      - name: Build libraries
        run: cd /tmp/infra && pwsh .\ce_install.ps1 --staging-dir "C:/tmp/staging" --dest "C:/tmp/staging" --enable windows build --temp-install --buildfor vcpp_v19_40_VS17_10_x64 'fmt 11.0.0'
