name: Library Builds for Windows compilers

on:
    workflow_dispatch:

jobs:
    librarybuild:
      runs-on: ['win-builder']

      steps:
      - name: Do everything
        run: Set-Location "C:\tmp"; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/compiler-explorer/infra/63feee2732b4b065b89645072dd23f18a326aa13/init/start-builder.ps1" -OutFile "C:\tmp\start-builder.ps1"; pwsh .\start-builder.ps1; $env:CONAN_USER = "ce"; $env:CONAN_PASSWORD = "${{ secrets.CONAN_PASSWORD }}"; Set-Location "C:\tmp\infra"; git checkout library-build-windows; $env:PATH = "$env:PATH;C:\BuildTools\Python;C:\BuildTools\Python\Scripts;C:\BuildTools\Ninja;Z:\compilers\windows-kits-10\bin;C:\BuildTools\CMake\bin;Z:\compilers\mingw-w64-13.1.0-16.0.2-11.0.0-ucrt-r1\bin;C:\Program Files\Amazon\AWSCLIV2"; conan user ce -p -r=ceserver; pwsh .\ce_install.ps1 --staging-dir "C:/tmp/staging" --dest "C:/tmp/staging" --enable windows build --temp-install --buildfor vcpp_v19_40_VS17_10_x64 'fmt 11.0.0'
